# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.30

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = C:\mingw64\bin\cmake.exe

# The command to remove a file.
RM = C:\mingw64\bin\cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\LordN.NASHOU\Desktop\code\ASHB2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\LordN.NASHOU\Desktop\code\ASHB2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	C:\mingw64\bin\cmake.exe -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	C:\mingw64\bin\cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\LordN.NASHOU\Desktop\code\ASHB2\CMakeFiles C:\Users\LordN.NASHOU\Desktop\code\ASHB2\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\LordN.NASHOU\Desktop\code\ASHB2\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named app

# Build rule for target.
app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 app
.PHONY : app

# fast build rule for target.
app/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/build
.PHONY : app/fast

libs/imgui/backends/imgui_impl_glfw.obj: libs/imgui/backends/imgui_impl_glfw.cpp.obj
.PHONY : libs/imgui/backends/imgui_impl_glfw.obj

# target to build an object file
libs/imgui/backends/imgui_impl_glfw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/backends/imgui_impl_glfw.cpp.obj
.PHONY : libs/imgui/backends/imgui_impl_glfw.cpp.obj

libs/imgui/backends/imgui_impl_glfw.i: libs/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : libs/imgui/backends/imgui_impl_glfw.i

# target to preprocess a source file
libs/imgui/backends/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/backends/imgui_impl_glfw.cpp.i
.PHONY : libs/imgui/backends/imgui_impl_glfw.cpp.i

libs/imgui/backends/imgui_impl_glfw.s: libs/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : libs/imgui/backends/imgui_impl_glfw.s

# target to generate assembly for a file
libs/imgui/backends/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/backends/imgui_impl_glfw.cpp.s
.PHONY : libs/imgui/backends/imgui_impl_glfw.cpp.s

libs/imgui/backends/imgui_impl_opengl3.obj: libs/imgui/backends/imgui_impl_opengl3.cpp.obj
.PHONY : libs/imgui/backends/imgui_impl_opengl3.obj

# target to build an object file
libs/imgui/backends/imgui_impl_opengl3.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/backends/imgui_impl_opengl3.cpp.obj
.PHONY : libs/imgui/backends/imgui_impl_opengl3.cpp.obj

libs/imgui/backends/imgui_impl_opengl3.i: libs/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : libs/imgui/backends/imgui_impl_opengl3.i

# target to preprocess a source file
libs/imgui/backends/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/backends/imgui_impl_opengl3.cpp.i
.PHONY : libs/imgui/backends/imgui_impl_opengl3.cpp.i

libs/imgui/backends/imgui_impl_opengl3.s: libs/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : libs/imgui/backends/imgui_impl_opengl3.s

# target to generate assembly for a file
libs/imgui/backends/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/backends/imgui_impl_opengl3.cpp.s
.PHONY : libs/imgui/backends/imgui_impl_opengl3.cpp.s

libs/imgui/imgui.obj: libs/imgui/imgui.cpp.obj
.PHONY : libs/imgui/imgui.obj

# target to build an object file
libs/imgui/imgui.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/imgui.cpp.obj
.PHONY : libs/imgui/imgui.cpp.obj

libs/imgui/imgui.i: libs/imgui/imgui.cpp.i
.PHONY : libs/imgui/imgui.i

# target to preprocess a source file
libs/imgui/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/imgui.cpp.i
.PHONY : libs/imgui/imgui.cpp.i

libs/imgui/imgui.s: libs/imgui/imgui.cpp.s
.PHONY : libs/imgui/imgui.s

# target to generate assembly for a file
libs/imgui/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/imgui.cpp.s
.PHONY : libs/imgui/imgui.cpp.s

libs/imgui/imgui_draw.obj: libs/imgui/imgui_draw.cpp.obj
.PHONY : libs/imgui/imgui_draw.obj

# target to build an object file
libs/imgui/imgui_draw.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/imgui_draw.cpp.obj
.PHONY : libs/imgui/imgui_draw.cpp.obj

libs/imgui/imgui_draw.i: libs/imgui/imgui_draw.cpp.i
.PHONY : libs/imgui/imgui_draw.i

# target to preprocess a source file
libs/imgui/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/imgui_draw.cpp.i
.PHONY : libs/imgui/imgui_draw.cpp.i

libs/imgui/imgui_draw.s: libs/imgui/imgui_draw.cpp.s
.PHONY : libs/imgui/imgui_draw.s

# target to generate assembly for a file
libs/imgui/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/imgui_draw.cpp.s
.PHONY : libs/imgui/imgui_draw.cpp.s

libs/imgui/imgui_tables.obj: libs/imgui/imgui_tables.cpp.obj
.PHONY : libs/imgui/imgui_tables.obj

# target to build an object file
libs/imgui/imgui_tables.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/imgui_tables.cpp.obj
.PHONY : libs/imgui/imgui_tables.cpp.obj

libs/imgui/imgui_tables.i: libs/imgui/imgui_tables.cpp.i
.PHONY : libs/imgui/imgui_tables.i

# target to preprocess a source file
libs/imgui/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/imgui_tables.cpp.i
.PHONY : libs/imgui/imgui_tables.cpp.i

libs/imgui/imgui_tables.s: libs/imgui/imgui_tables.cpp.s
.PHONY : libs/imgui/imgui_tables.s

# target to generate assembly for a file
libs/imgui/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/imgui_tables.cpp.s
.PHONY : libs/imgui/imgui_tables.cpp.s

libs/imgui/imgui_widgets.obj: libs/imgui/imgui_widgets.cpp.obj
.PHONY : libs/imgui/imgui_widgets.obj

# target to build an object file
libs/imgui/imgui_widgets.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/imgui_widgets.cpp.obj
.PHONY : libs/imgui/imgui_widgets.cpp.obj

libs/imgui/imgui_widgets.i: libs/imgui/imgui_widgets.cpp.i
.PHONY : libs/imgui/imgui_widgets.i

# target to preprocess a source file
libs/imgui/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/imgui_widgets.cpp.i
.PHONY : libs/imgui/imgui_widgets.cpp.i

libs/imgui/imgui_widgets.s: libs/imgui/imgui_widgets.cpp.s
.PHONY : libs/imgui/imgui_widgets.s

# target to generate assembly for a file
libs/imgui/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/libs/imgui/imgui_widgets.cpp.s
.PHONY : libs/imgui/imgui_widgets.cpp.s

src/Disease.obj: src/Disease.cpp.obj
.PHONY : src/Disease.obj

# target to build an object file
src/Disease.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/Disease.cpp.obj
.PHONY : src/Disease.cpp.obj

src/Disease.i: src/Disease.cpp.i
.PHONY : src/Disease.i

# target to preprocess a source file
src/Disease.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/Disease.cpp.i
.PHONY : src/Disease.cpp.i

src/Disease.s: src/Disease.cpp.s
.PHONY : src/Disease.s

# target to generate assembly for a file
src/Disease.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/Disease.cpp.s
.PHONY : src/Disease.cpp.s

src/Entity.obj: src/Entity.cpp.obj
.PHONY : src/Entity.obj

# target to build an object file
src/Entity.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/Entity.cpp.obj
.PHONY : src/Entity.cpp.obj

src/Entity.i: src/Entity.cpp.i
.PHONY : src/Entity.i

# target to preprocess a source file
src/Entity.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/Entity.cpp.i
.PHONY : src/Entity.cpp.i

src/Entity.s: src/Entity.cpp.s
.PHONY : src/Entity.s

# target to generate assembly for a file
src/Entity.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/Entity.cpp.s
.PHONY : src/Entity.cpp.s

src/SpatialMesh.obj: src/SpatialMesh.cpp.obj
.PHONY : src/SpatialMesh.obj

# target to build an object file
src/SpatialMesh.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/SpatialMesh.cpp.obj
.PHONY : src/SpatialMesh.cpp.obj

src/SpatialMesh.i: src/SpatialMesh.cpp.i
.PHONY : src/SpatialMesh.i

# target to preprocess a source file
src/SpatialMesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/SpatialMesh.cpp.i
.PHONY : src/SpatialMesh.cpp.i

src/SpatialMesh.s: src/SpatialMesh.cpp.s
.PHONY : src/SpatialMesh.s

# target to generate assembly for a file
src/SpatialMesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/SpatialMesh.cpp.s
.PHONY : src/SpatialMesh.cpp.s

src/UI.obj: src/UI.cpp.obj
.PHONY : src/UI.obj

# target to build an object file
src/UI.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/UI.cpp.obj
.PHONY : src/UI.cpp.obj

src/UI.i: src/UI.cpp.i
.PHONY : src/UI.i

# target to preprocess a source file
src/UI.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/UI.cpp.i
.PHONY : src/UI.cpp.i

src/UI.s: src/UI.cpp.s
.PHONY : src/UI.s

# target to generate assembly for a file
src/UI.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/UI.cpp.s
.PHONY : src/UI.cpp.s

src/implem_free_will.obj: src/implem_free_will.cpp.obj
.PHONY : src/implem_free_will.obj

# target to build an object file
src/implem_free_will.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/implem_free_will.cpp.obj
.PHONY : src/implem_free_will.cpp.obj

src/implem_free_will.i: src/implem_free_will.cpp.i
.PHONY : src/implem_free_will.i

# target to preprocess a source file
src/implem_free_will.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/implem_free_will.cpp.i
.PHONY : src/implem_free_will.cpp.i

src/implem_free_will.s: src/implem_free_will.cpp.s
.PHONY : src/implem_free_will.s

# target to generate assembly for a file
src/implem_free_will.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/implem_free_will.cpp.s
.PHONY : src/implem_free_will.cpp.s

src/main.obj: src/main.cpp.obj
.PHONY : src/main.obj

# target to build an object file
src/main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/main.cpp.obj
.PHONY : src/main.cpp.obj

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\app.dir\build.make CMakeFiles/app.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... app
	@echo ... libs/imgui/backends/imgui_impl_glfw.obj
	@echo ... libs/imgui/backends/imgui_impl_glfw.i
	@echo ... libs/imgui/backends/imgui_impl_glfw.s
	@echo ... libs/imgui/backends/imgui_impl_opengl3.obj
	@echo ... libs/imgui/backends/imgui_impl_opengl3.i
	@echo ... libs/imgui/backends/imgui_impl_opengl3.s
	@echo ... libs/imgui/imgui.obj
	@echo ... libs/imgui/imgui.i
	@echo ... libs/imgui/imgui.s
	@echo ... libs/imgui/imgui_draw.obj
	@echo ... libs/imgui/imgui_draw.i
	@echo ... libs/imgui/imgui_draw.s
	@echo ... libs/imgui/imgui_tables.obj
	@echo ... libs/imgui/imgui_tables.i
	@echo ... libs/imgui/imgui_tables.s
	@echo ... libs/imgui/imgui_widgets.obj
	@echo ... libs/imgui/imgui_widgets.i
	@echo ... libs/imgui/imgui_widgets.s
	@echo ... src/Disease.obj
	@echo ... src/Disease.i
	@echo ... src/Disease.s
	@echo ... src/Entity.obj
	@echo ... src/Entity.i
	@echo ... src/Entity.s
	@echo ... src/SpatialMesh.obj
	@echo ... src/SpatialMesh.i
	@echo ... src/SpatialMesh.s
	@echo ... src/UI.obj
	@echo ... src/UI.i
	@echo ... src/UI.s
	@echo ... src/implem_free_will.obj
	@echo ... src/implem_free_will.i
	@echo ... src/implem_free_will.s
	@echo ... src/main.obj
	@echo ... src/main.i
	@echo ... src/main.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

